# Generated by Django 6.0.1 on 2026-01-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='interests',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
